[package]
name = "v8test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.107.0"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
log = "0.4"
anyhow = "1.0"